spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/testkb
    username: dratuti
    password: dratuti

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 7373
